//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureStoreFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rawmaterial
    {
        public int id { get; set; }
        public string CompanyName { get; set; }
        public string ProductName { get; set; }
        public string Size { get; set; }
        public string Qty { get; set; }
        public string Price { get; set; }
    }
}
